ALL_WALLS_CLOSED = 15
NORTH = 1
EAST = 2
SOUTH = 4
WEST = 8
DIRECTION_STEP = {NORTH: (0, -1), EAST: (1, 0), SOUTH: (0, 1), WEST: (-1, 0)}
DIRECTION_OPPOSITE = {NORTH: SOUTH, EAST: WEST, SOUTH: NORTH, WEST: EAST}
